name: Build and Release

on:
  push:
    tags:
      - 'test-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - name: Build binary
        run: |
          sudo apt update && sudo apt install -yqq libgpgme-dev btrfs-progs libbtrfs-dev
          make binary
          mv ./bin/prometheus-podman-exporter ./bin/prometheus-podman-exporter-${{ matrix.goarch }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/prometheus-podman-exporter-${{ matrix.goarch }}
          asset_name: prometheus-podman-exporter-${{ matrix.goarch }}-${{ github.ref }}
          asset_content_type: application/octet-stream