name: Build and Release

on:
  push:
    tags:
      - 'test-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Build binary
        run: |
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV
          sudo apt update && sudo apt install -yqq libgpgme-dev btrfs-progs libbtrfs-dev
          make binary
          go mod download
          mv ./bin/prometheus-podman-exporter ./bin/prometheus-podman-exporter-${{ matrix.goarch }}

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-podman-exporter-${{ matrix.goarch }}
          path: |
            /bin/prometheus-podman-exporter-${{ matrix.goarch }}
  
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: prometheus-podman-exporter-${{ matrix.goarch }}
          tag: ${{ github.ref }}
          file_glob: true